
import { Inter } from 'next/font/google'
import './globals.css'
import { Poppins } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight:'400'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
         
      <body className={poppins.className}>{children}</body>
    
    </html>
  )
}
